version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/simple-web-server
permissions:
  - object: simple-web-server/scripts/start_server.sh
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: simple-web-server/scripts/start_server.sh
      timeout: 40
      runas: root
